// samples/angular-starter/src/app/app.component.ts
import { Component } from '@angular/core';
import type { CellData, Report } from '@proteus/propivot';
import { ProPivotComponent } from './pro-pivot.component';
import { buildReport, generateRows } from './sample-data';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [ProPivotComponent],
  template: `
    <div class="page">
      <header class="bar">
        <strong>ProPivot · Angular starter</strong>
        <span class="muted">{{ rowCount.toLocaleString() }} rows · client-side</span>
      </header>

      <!-- Drag fields, double-click a cell to drill through, use the toolbar to export. -->
      <pro-pivot
        class="grid"
        [report]="report"
        [toolbar]="true"
        (cellclick)="onCellClick($event)">
      </pro-pivot>
    </div>
  `,
  styles: [`
    .page { height: 100%; display: flex; flex-direction: column; }
    .bar {
      display: flex; align-items: center; gap: 12px;
      padding: 10px 16px; border-bottom: 1px solid #e6e9f0; background: #fff;
    }
    .bar .muted { color: #5b6478; font-size: 13px; }
    .grid { flex: 1; min-height: 0; }
  `],
})
export class AppComponent {
  readonly rowCount = 20_000;
  readonly report: Report = buildReport(generateRows(this.rowCount));

  onCellClick(cell: CellData): void {
    console.log('cell clicked', cell);
  }
}

// samples/react-starter/src/App.tsx
import { useMemo, useState } from 'react';
// The pivot grid styles. Resolved from the @proteus/propivot package exports.
import '@proteus/propivot/propivot.css';
// `Pivot` is the React wrapper; `ProPivot` is the underlying instance type.
import { Pivot, type ProPivot } from '@proteus/propivot/react';
import { generateRows, buildReport } from './sampleData';

export default function App() {
  // Generate the dataset once; rebuild the report only when the data changes.
  const [rowCount] = useState(20_000);
  const data = useMemo(() => generateRows(rowCount), [rowCount]);
  const report = useMemo(() => buildReport(data), [data]);

  const [pivot, setPivot] = useState<ProPivot | null>(null);

  return (
    <div className="page">
      <header className="bar">
        <strong>ProPivot · React starter</strong>
        <span className="muted">{data.length.toLocaleString()} rows · client-side</span>
        <div className="spacer" />
        <button onClick={() => pivot?.expandAllData()}>Expand</button>
        <button onClick={() => pivot?.collapseAllData()}>Collapse</button>
        <button onClick={() => pivot?.exportTo('csv', { filename: 'propivot' })}>CSV</button>
        <button onClick={() => pivot?.exportTo('excel', { filename: 'propivot', excelSheetName: 'Report' })}>
          Excel
        </button>
      </header>

      {/* The grid fills the remaining height. Drag fields, double-click a cell to drill through, export. */}
      <Pivot
        report={report}
        toolbar
        className="grid"
        onReady={(p) => setPivot(p)}
      />
    </div>
  );
}
